name: 'Unit test runner'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on:
      - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      
      - name: Install
        run: npm install
      
      - name: Build
        run: npm run res:build

      - name: Run tests
        run: npm run res:test
